// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const changeTaskStatusById = `-- name: ChangeTaskStatusById :one
update tbl_tasks set task_status = $1, updated_at = NOW() where id = $2
RETURNING id, title, description, task_status, deadline, owner_id, created_at, updated_at
`

type ChangeTaskStatusByIdParams struct {
	TaskStatus Status `json:"task_status"`
	ID         int32  `json:"id"`
}

func (q *Queries) ChangeTaskStatusById(ctx context.Context, arg ChangeTaskStatusByIdParams) (TblTask, error) {
	row := q.db.QueryRow(ctx, changeTaskStatusById, arg.TaskStatus, arg.ID)
	var i TblTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TaskStatus,
		&i.Deadline,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
insert into tbl_tasks(title, description, task_status, deadline, owner_id)
values($1,$2,$3,$4,$5)
RETURNING id, title, description, task_status, deadline, owner_id, created_at, updated_at
`

type CreateTaskParams struct {
	Title       string           `json:"title"`
	Description pgtype.Text      `json:"description"`
	TaskStatus  Status           `json:"task_status"`
	Deadline    pgtype.Timestamp `json:"deadline"`
	OwnerID     int32            `json:"owner_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (TblTask, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.TaskStatus,
		arg.Deadline,
		arg.OwnerID,
	)
	var i TblTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TaskStatus,
		&i.Deadline,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
delete from tbl_tasks where id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const extendDeadlineById = `-- name: ExtendDeadlineById :one
update tbl_tasks set deadline = $1, updated_at = NOW() where id = $2
RETURNING id, title, description, task_status, deadline, owner_id, created_at, updated_at
`

type ExtendDeadlineByIdParams struct {
	Deadline pgtype.Timestamp `json:"deadline"`
	ID       int32            `json:"id"`
}

func (q *Queries) ExtendDeadlineById(ctx context.Context, arg ExtendDeadlineByIdParams) (TblTask, error) {
	row := q.db.QueryRow(ctx, extendDeadlineById, arg.Deadline, arg.ID)
	var i TblTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TaskStatus,
		&i.Deadline,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskById = `-- name: GetTaskById :one
select id, title, description, task_status, deadline, owner_id, created_at, updated_at from tbl_tasks where id = $1 limit 1
`

func (q *Queries) GetTaskById(ctx context.Context, id int32) (TblTask, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i TblTask
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TaskStatus,
		&i.Deadline,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskByUser = `-- name: ListTaskByUser :many
select id, title, description, task_status, deadline, owner_id, created_at, updated_at from tbl_tasks where owner_id = $1
`

func (q *Queries) ListTaskByUser(ctx context.Context, ownerID int32) ([]TblTask, error) {
	rows, err := q.db.Query(ctx, listTaskByUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblTask
	for rows.Next() {
		var i TblTask
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TaskStatus,
			&i.Deadline,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
