// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into tbl_users(name, email, password_hash) 
values ($1, $2, $3)
RETURNING id, name, email, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (TblUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, email, password_hash, created_at, updated_at from tbl_users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (TblUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, name, email, password_hash, created_at, updated_at from tbl_users where id = $1 limit 1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (TblUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i TblUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersList = `-- name: GetUsersList :many
select id, name, email, password_hash, created_at, updated_at from tbl_users order by id desc
`

func (q *Queries) GetUsersList(ctx context.Context) ([]TblUser, error) {
	rows, err := q.db.Query(ctx, getUsersList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblUser
	for rows.Next() {
		var i TblUser
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
